### ISSUE TITLE
A suggestion for callback

### ISSUE THREAD

**Issue by amovah** [yoshuawuyts/copy-template-dir#1]
I think, It's much better to use Promise instead of callback.
like this:

``` js

copy(inDir, outDir, vars).then(() => {
  console.log('done');
}).catch(err => { throw err; });

```

And I'm interested in to do that.

**Comment by yoshuawuyts** [comment]
I disagree, Promises mangle stack traces and squash errors. I will never voluntarily use Promises as they are currently defined in the spec. That said: it's trivial to wrap a callback into a Promise (or any other control flow library):

``` js
const toPromise = require('es6-promisify')
const copy = require('copy-template-dir')

toPromise(copy(inDir, outDir, vars))
  .then(() => console.log('done'))
  .catch(err => throw err)
```

Cheers!
