### ISSUE TITLE
Rename all leading _ files

### ISSUE THREAD

**Issue by insin** [yoshuawuyts/copy-template-dir#4]
Would it be possible to extend renaming of `_` prefixed files to include _all_ files with the prefix, not just dotfiles?

I just discovered that npm will read nested package.json files in your project, which caused this packaging issue with some templates I was providing: insin/nwb#21

To avoid this,  I would need to rename `package.json` files which will be copied by copy-template-dir to `_package.json`.

I can create a PR for this later if you're ok with the proposed change.

**Comment by yoshuawuyts** [comment]
I'd be happy to get a PR for this in.

**Comment by yoshuawuyts** [comment]
Released as `v1.1.0`.
