### ISSUE TITLE
No errors with a non-existent srcDir

### ISSUE THREAD

**Issue by insin** [yoshuawuyts/copy-template-dir#7]
Just something which came up today using copy-template-dir@1.2.0:

I moved some code up a directory and forgot to change the relative path it was using to find my template directory, but I didn't get an error callback from copy-template-dir due to the non-existent directory.

It seems like copy-template-dir is eating errors from `readdirp` because it's using the streaming interface and there's no `.on('error' ...)` handler.

What's your preferred solution to this?
- Check that srcDir exists in `copyTemplateDir` and bail out early.
- Add an error handler for the `readdirp` stream (it seems it attempts 2 file operations before returning the stream - I saw 2 errors when I tried this quickly in my `node_modules/copy-template-dir`)

**Comment by insin** [comment]
Ignore me, sanity checking in the Node REPL indicates this was a problem elsewhere!

```
> var copy = require('copy-template-dir')
undefined
> copy('/foobaz', '.', {}, function() { console.log(arguments) })
undefined
> { '0':
   { [Error: ENOENT: no such file or directory, lstat 'C:\foobaz']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'lstat',
     path: 'C:\\foobaz' } }
```

**Comment by yoshuawuyts** [comment]
hah, it seems like you've got a good interest in this package. Added you as a collaborator here + on [`maxstache`](https://github.com/yoshuawuyts/maxstache) / [`maxstache-stream`](https://github.com/yoshuawuyts/maxstache-stream). Cheers!
